# Generated by Django 4.1.5 on 2023-02-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_country_remove_user_city_stateprovince_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="state",
            new_name="state_province",
        ),
    ]
