# Generated by Django 4.1.5 on 2023-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
