# Generated by Django 4.1.5 on 2023-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_user_city_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
