# Generated by Django 4.1.5 on 2023-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_rename_state_user_state_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
