# Generated by Django 4.1.5 on 2023-02-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_country_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="countryCode",
            new_name="country_code",
        ),
        migrations.RenameField(
            model_name="country",
            old_name="countryCodeAlpha3",
            new_name="country_code_alpha3",
        ),
    ]
