# Generated by Django 4.1.5 on 2023-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved_to_be_in_touch",
            field=models.BooleanField(default=False),
        ),
    ]
