# Generated by Django 5.0.8 on 2024-09-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_billaddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billaddress",
            options={
                "verbose_name": "Bill Address",
                "verbose_name_plural": "Bill Addresses",
            },
        ),
        migrations.RemoveField(
            model_name="billaddress",
            name="addr_state",
        ),
        migrations.AddField(
            model_name="billaddress",
            name="state_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
