# Generated by Django 5.0.8 on 2024-09-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_billaddress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billaddress",
            name="city",
        ),
        migrations.AddField(
            model_name="billaddress",
            name="state_province",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="management.stateprovince",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stateprovince",
            name="iso_code",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="billaddress",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management.country"
            ),
        ),
    ]
