# Generated by Django 5.0.8 on 2024-09-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0008_remove_billaddress_city_billaddress_state_province_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stateprovince",
            name="iso_code",
            field=models.CharField(default="", max_length=50),
        ),
    ]
