# Generated by Django 5.0.8 on 2024-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_alter_stateprovince_iso_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stateprovince",
            old_name="iso_code",
            new_name="state_code",
        ),
    ]
