# Generated by Django 5.0.8 on 2024-09-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_rename_iso_code_stateprovince_state_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="stateprovince",
            options={
                "verbose_name": "StateProvince",
                "verbose_name_plural": "StateProvinces",
            },
        ),
    ]
