# Generated by Django 5.0.8 on 2024-09-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0012_alter_billaddress_add_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="billaddress",
            name="country_code",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
