# Generated by Django 5.0.8 on 2024-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_billaddress_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billaddress",
            name="country_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
