# Generated by Django 4.1.5 on 2023-01-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donation_category/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donation_item/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=255)),
                ("merchant_order_id", models.TextField(blank=True, null=True)),
                ("md_code", models.CharField(blank=True, max_length=300, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "is_complete",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status_code",
                    models.CharField(blank=True, default="-1", max_length=3, null=True),
                ),
                (
                    "status_code_description",
                    models.CharField(
                        blank=True,
                        default="Response not received from bank",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "donation_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donor.donationitem",
                    ),
                ),
            ],
        ),
    ]
