# Generated by Django 4.1.5 on 2023-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationitem",
            name="donation_type",
            field=models.CharField(
                choices=[("Dynamic", "Dynamic"), ("Static", "Static")],
                default="Dynamic",
                max_length=7,
            ),
        ),
    ]
