# Generated by Django 4.1.5 on 2023-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationtransaction",
            name="donation_item",
        ),
        migrations.AddField(
            model_name="donationtransaction",
            name="donation_item",
            field=models.ManyToManyField(null=True, to="donor.donationitem"),
        ),
    ]
