# Generated by Django 4.1.5 on 2023-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_donationitem_donation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationitem",
            name="quantity_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
