# Generated by Django 4.1.5 on 2023-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_donationitem_quantity_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="donation_category/"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=500)),
                ("branch", models.CharField(max_length=500)),
                ("branch_no", models.IntegerField()),
                ("swift_no", models.CharField(max_length=500)),
                ("iban_no", models.CharField(max_length=500)),
                (
                    "currency",
                    models.CharField(
                        choices=[("TRY", "TRY"), ("USD", "USD"), ("EUR", "EUR")],
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
    ]
