# Generated by Django 4.1.5 on 2023-02-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_bank_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="donor.bank",
            ),
            preserve_default=False,
        ),
    ]
