# Generated by Django 4.1.5 on 2023-01-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0005_alter_donationcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="donor.donationcategory",
            ),
        ),
    ]
