# Generated by Django 4.1.5 on 2023-03-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0007_alter_donationcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="branch",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="branch_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban_no",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="swift_no",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
