# Generated by Django 4.1.5 on 2023-01-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0007_remove_donationtransaction_donation_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationtransaction",
            name="donations",
        ),
        migrations.AddField(
            model_name="donation",
            name="donation_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="donor.donationtransaction",
            ),
        ),
    ]
