# Generated by Django 4.1.5 on 2023-01-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_alter_cart_user"),
        ("donor", "0009_donation_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                related_query_name="donations",
                to="payment.cart",
            ),
        ),
    ]
