# Generated by Django 4.1.9 on 2023-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0009_alter_bankaccount_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcategory",
            name="order",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
