# Generated by Django 4.1.9 on 2023-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0010_donationcategory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="order",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
