# Generated by Django 4.1.5 on 2023-01-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0010_alter_donation_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="donor.donationtransaction",
            ),
        ),
    ]
