# Generated by Django 4.1.5 on 2023-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0011_alter_donation_donation_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donation_transaction",
        ),
        migrations.AddField(
            model_name="donationtransaction",
            name="donations",
            field=models.ManyToManyField(to="donor.donation"),
        ),
    ]
