# Generated by Django 4.1.5 on 2023-01-29 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0012_remove_donation_donation_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="added_time",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
