# Generated by Django 4.1.9 on 2023-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0012_alter_bank_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationcategory",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
