# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0013_donation_added_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="cart",
        ),
    ]
