# Generated by Django 4.1.5 on 2023-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0015_donation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationtransaction",
            name="amount_sent_to_bank",
            field=models.CharField(default="", max_length=299),
            preserve_default=False,
        ),
    ]
