# Generated by Django 4.1.5 on 2023-02-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0016_donationtransaction_amount_sent_to_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationtransaction",
            name="donations",
        ),
        migrations.AddField(
            model_name="donation",
            name="donation_transaction",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="donor.donationtransaction",
            ),
            preserve_default=False,
        ),
    ]
