# Generated by Django 4.1.5 on 2023-02-01 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        related_query_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_provider", models.BooleanField(default=False)),
                ("code_name", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Payment Provider",
                "verbose_name_plural": "Payment Providers",
            },
        ),
        migrations.CreateModel(
            name="DonationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("amount_sent_to_bank", models.CharField(max_length=299)),
                ("merchant_order_id", models.TextField(blank=True, null=True)),
                ("md_code", models.CharField(blank=True, max_length=300, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "is_complete",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status_code",
                    models.CharField(blank=True, default="-1", max_length=3, null=True),
                ),
                (
                    "status_code_description",
                    models.CharField(
                        blank=True,
                        default="Response not received from bank",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation Transaction",
                "verbose_name_plural": "Donation Transactions",
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_time",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "donation_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donor.donationitem",
                    ),
                ),
                (
                    "donation_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="payment.donationtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="payment.cart",
                    ),
                ),
                (
                    "donation_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donor.donationitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
    ]
