# Generated by Django 4.1.5 on 2023-01-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentprovider_is_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentprovider",
            options={
                "verbose_name": "Payment Provider",
                "verbose_name_plural": "Payment Providers",
            },
        ),
    ]
