# Generated by Django 4.1.5 on 2023-02-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_rename_name_donorprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="donationtransaction",
            name="user",
        ),
        migrations.AddField(
            model_name="donation",
            name="donor_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.donorprofile",
            ),
        ),
        migrations.AddField(
            model_name="donationtransaction",
            name="donor_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.donorprofile",
            ),
        ),
    ]
