# Generated by Django 4.1.5 on 2023-01-28 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0008_remove_donationtransaction_donations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0003_alter_paymentprovider_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("donations", models.ManyToManyField(to="donor.donation")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
    ]
