# Generated by Django 4.1.5 on 2023-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0008_remove_donationtransaction_donations_and_more"),
        ("payment", "0004_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="cart",
            name="donations",
            field=models.ManyToManyField(null=True, to="donor.donation"),
        ),
    ]
