# Generated by Django 4.1.5 on 2023-02-01 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0004_remove_donation_user_remove_donationtransaction_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '+[country code][phone number]'",
                        regex="^\\+\\d{1,3}\\d{1,15}$",
                    )
                ],
            ),
        ),
    ]
