# Generated by Django 4.1.5 on 2023-01-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_cart_amount_alter_cart_donations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="donations",
        ),
    ]
