# Generated by Django 4.1.5 on 2023-02-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_rename_donor_profile_donation_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationtransaction",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="donationtransaction",
            name="last_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
