# Generated by Django 4.1.5 on 2023-02-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_alter_donationtransaction_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationtransaction",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
