# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0014_remove_donation_cart"),
        ("payment", "0010_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="donations",
            field=models.ManyToManyField(
                related_name="cart", related_query_name="cart", to="donor.donation"
            ),
        ),
    ]
