# Generated by Django 4.1.5 on 2023-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_rename_phone_donationtransaction_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationtransaction",
            name="donation_type",
            field=models.CharField(
                choices=[("WEB", "WEB")], default="WEB", max_length=10
            ),
        ),
    ]
