# Generated by Django 4.1.5 on 2023-02-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_donationtransaction_donation_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationtransaction",
            old_name="donation_type",
            new_name="donation_platform",
        ),
    ]
