# Generated by Django 4.1.5 on 2023-01-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_remove_cart_donations_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="payment.cart",
            ),
        ),
    ]
