# Generated by Django 4.1.5 on 2023-02-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_donationitem_quantity_price"),
        ("payment", "0012_rename_donation_type_donationtransaction_donation_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="donor.donationitem",
            ),
        ),
    ]
