# Generated by Django 4.1.5 on 2023-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_alter_donation_donation_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationtransaction",
            name="group_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="donationtransaction",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
