# Generated by Django 4.1.5 on 2023-01-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
    ]
