# Generated by Django 4.1.5 on 2023-01-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0015_alter_cartitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="code_name",
            field=models.CharField(default="KT", max_length=3),
            preserve_default=False,
        ),
    ]
