# Generated by Django 4.1.5 on 2023-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0015_alter_donationtransaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationtransaction",
            name="status_code",
            field=models.CharField(blank=True, default="-1", max_length=10, null=True),
        ),
    ]
