# Generated by Django 4.1.5 on 2023-03-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0016_alter_donationtransaction_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationtransaction",
            name="donation_platform",
            field=models.CharField(
                choices=[("WEB", "WEB")], default="WEB", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="donationtransaction",
            name="status_code",
            field=models.CharField(blank=True, default="-1", max_length=255, null=True),
        ),
    ]
