# Generated by Django 5.0.8 on 2024-09-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0019_billaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillAddress",
        ),
    ]
