# Generated by Django 5.0.8 on 2024-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0021_donationtransaction_add_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationtransaction",
            name="add_line",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
