# Generated by Django 5.0.8 on 2024-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0022_alter_donationtransaction_add_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationtransaction",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
