name: CD - Deploy to Test Server

on:
  workflow_run:
    workflows: ["CI - Image Deploy To Docker Hub"]
    branches: [main]
    types:
      - completed

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: CD & Execute restart.sh
        run: cd /home/ihyaadmin/bagis; bash /home/ihyaadmin/bagis/restart.sh
