name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"

jobs:
  code-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Add this step to check out your source code
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Choose your desired Python version
      - name: Install dependencies
        run: pip install -r src/requirements.txt  # Install your app's dependencies
      - name: Create .env file # Create a .env file for your development environment
        run: mv src/.env.dev src/.env
      - name: Run pytest
        run: pytest src # Adjust this command to run your pytest tests
        env:
          DEBUG: 1 # Set any environment variables required by your tests

  docker-main:
    needs: code-test
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    uses: ./.github/workflows/reuse-docker-build-push.yml
    with:
      docker-context: /src
      image-tag: latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-develop:
    needs: code-test
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    uses: ./.github/workflows/reuse-docker-build-push.yml
    with:
      docker-context: /src
      image-tag: develop
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
  docker-feature:
    needs: code-test
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    uses: ./.github/workflows/reuse-docker-build-push.yml
    with:
      docker-context: /src
      image-tag: feature-${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}