name: CI - Image Deploy To Docker Hub

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4  # Add this step to check out your source code
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Choose your desired Python version
      - name: Install dependencies
        run: pip install -r src/requirements.txt  # Install your app's dependencies
      - name: Create .env file # Create a .env file for your development environment
        run: mv src/.env.dev src/.env
      - name: Run pytest
        run: pytest src # Adjust this command to run your pytest tests
        env:
          DEBUG: 1 # Set any environment variables required by your tests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "${{github.workspace}}/src"  # Use the correct context path
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest
