name: Docker Image Build & Push

on:
  workflow_call:
    inputs:
        docker-context:
            required: true
            type: string
            description: 'The path to the Docker context'
        image-tag:
            required: true
            type: string
            description: 'The tag for the Docker image'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    - name:
      run: |
        echo "Building Docker image"
        echo "Docker context: ${{ inputs.docker-context }}"
        echo "Image tag: ${{ inputs.image-tag }}"
        ls -la
      shell: bash
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "${{ inputs.docker-context }}"  
        push: true
        tags: mebaysan/donation-app:${{ inputs.image-tag }}
